- Resources:
    - FEDIAF Guidelines:
        - href: https://europeanpetfood.org/self-regulation/nutrition/
          icon: mdi-book-open-variant
    - EU Regulation 767/2009:
        - href: https://eur-lex.europa.eu/legal-content/PL/TXT/?uri=CELEX:32009R0767
          icon: mdi-gavel
